import { useRef, useState } from "react";
import html2canvas from "html2canvas";
import Modal from "../common/Modal";
import type { TransactionSummary } from "../../types";
import { formatCurrency, monthLabel } from "../../utils/formatters";

type MonthlyReportModalProps = {
  isOpen: boolean;
  onClose: () => void;
  summary: TransactionSummary | null;
  month: string;
};

const COLORS = ["#4A90E2", "#9B59B6", "#F1C40F", "#E67E22", "#27AE60", "#1ABC9C", "#3498DB", "#E74C3C"];

function MonthlyReportModal({
  isOpen,
  onClose,
  summary,
  month
}: MonthlyReportModalProps) {
  const reportRef = useRef<HTMLDivElement>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownload = async () => {
    if (!reportRef.current) return;

    setIsGenerating(true);
    try {
      const canvas = await html2canvas(reportRef.current, {
        backgroundColor: "#ffffff",
        scale: 2,
        useCORS: true,
      });

      const link = document.createElement("a");
      link.download = `가계부_리포트_${month}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch (error) {
      console.error("리포트 생성 실패:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  if (!summary) return null;

  // 카테고리별 지출 데이터 (상위 8개)
  const categoryData = (summary.categories || [])
    .filter((item) => item.expense > 0)
    .sort((a, b) => b.expense - a.expense)
    .slice(0, 8);

  const totalExpense = categoryData.reduce((sum, item) => sum + item.expense, 0);

  return (
    <Modal open={isOpen} onClose={onClose} hideFooter>
      <div className="report-modal">
        <h3 className="report-modal__title">월간 지출 리포트</h3>

        {/* 리포트 영역 (이미지로 변환될 부분) */}
        <div ref={reportRef} className="report-content">
          <div className="report-header">
            <h2 className="report-header__title">{monthLabel(month)} 지출 리포트</h2>
            <p className="report-header__subtitle">내 가계부</p>
          </div>

          <div className="report-summary">
            <div className="report-summary__item report-summary__item--income">
              <span className="report-summary__label">총 수입</span>
              <span className="report-summary__value">{formatCurrency(summary.totalIncome)}원</span>
            </div>
            <div className="report-summary__item report-summary__item--expense">
              <span className="report-summary__label">총 지출</span>
              <span className="report-summary__value">{formatCurrency(summary.totalExpense)}원</span>
            </div>
            <div className="report-summary__item report-summary__item--balance">
              <span className="report-summary__label">잔액</span>
              <span className="report-summary__value">{formatCurrency(summary.balance)}원</span>
            </div>
          </div>

          {categoryData.length > 0 && (
            <div className="report-categories">
              <h3 className="report-section-title">카테고리별 지출</h3>
              <ul className="report-category-list">
                {categoryData.map((item, index) => {
                  const percentage = totalExpense > 0 ? (item.expense / totalExpense) * 100 : 0;
                  return (
                    <li key={item.category} className="report-category-item">
                      <div className="report-category-item__header">
                        <span
                          className="report-category-item__color"
                          style={{ backgroundColor: COLORS[index % COLORS.length] }}
                        />
                        <span className="report-category-item__name">{item.category}</span>
                        <span className="report-category-item__amount">{formatCurrency(item.expense)}원</span>
                        <span className="report-category-item__percent">{percentage.toFixed(1)}%</span>
                      </div>
                      <div className="report-category-item__bar">
                        <div
                          className="report-category-item__bar-fill"
                          style={{
                            width: `${percentage}%`,
                            backgroundColor: COLORS[index % COLORS.length]
                          }}
                        />
                      </div>
                    </li>
                  );
                })}
              </ul>
            </div>
          )}

          <div className="report-footer">
            <span>Generated by 내 가계부</span>
          </div>
        </div>

        <div className="report-modal__actions">
          <button
            type="button"
            className="report-modal__btn report-modal__btn--cancel"
            onClick={onClose}
          >
            닫기
          </button>
          <button
            type="button"
            className="report-modal__btn report-modal__btn--download"
            onClick={handleDownload}
            disabled={isGenerating}
          >
            {isGenerating ? "생성 중..." : "이미지 저장"}
          </button>
        </div>
      </div>
    </Modal>
  );
}

export default MonthlyReportModal;
